blog/urls.py
from django.conf.urls import url
from blog import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"

urlpatterns = [

    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^post/new/$',views.CreatePostView.as_view(),name='post_new'),
    url(r'^post/(?P<pk>[-\w]+)/$',views.PostDetailView.as_view(),name='post_detail'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>[-\w]+)/edit/$',views.PostUpdateView.as_view(),name='post_edit'),
    url(r'^post/(?P<pk>[-\w]+)/remove/$',views.PostDeleteView.as_view(),name='post_remove'),
    url(r'^drafts/$',views.PostDraftView.as_view(),name='post_draft_list'),
    url(r'^post/(?P<pk>[-\w]+)/comment/$',views.add_comment_to_post,name = 'add_comment_to_post'),
    url(r'^post/(?P<pk>[-\w]+)/publish/$',views.post_publish,name = 'post_publish'),
    url(r'^post/(?P<pk>[-\w]+)/like/$',views.add_like_to_post,name = 'like'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name = 'logout',kwargs = {'next_page':'/'})
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now())
    published_date = models.DateTimeField(blank = True,null = True)
    like = models.PositiveIntegerField(default = 0)

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def comment_count(self):
        return self.comments.all()

    def get_absolute_url(self):
        return reverse('blog:post_detail',kwargs = {'pk':self.pk})

    def likes(self):
        self.like += 1
        self.save()

class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name ='comments',on_delete = models.CASCADE)
    author = models.CharField(max_length = 200)
    text = models.TextField()
    create_date = models.DateTimeField(default = timezone.now())

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import *

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author','title','text')

        widgets = {

            'title':forms.TextInput(attrs = {'class':'textinputclass'}),
            'text':forms.Textarea(attrs = {'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author','text')


        widgets = {

            'author':forms.TextInput(attrs = {'class':'textinputclass'}),
            'text':forms.Textarea(attrs = {'class':'editable medium-editor-textarea'})
        }

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from blog.models import *
from blog.forms import *
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin,DeleteView):
    login_url = '/login/'
    model = Post
    success_url = reverse_lazy('blog:post_list')

class PostDraftView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'

    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = True).order_by('create_date')


def add_comment_to_post(request,pk):

    post = get_object_or_404(Post,pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.save()

            return redirect('blog:post_detail',pk=post.pk)

    else:
        form = CommentForm()

    return render(request,'blog/comment_form.html',{'form':form})

@login_required
def post_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)

def add_like_to_post(request,pk):
    like = get_object_or_404(Post,pk=pk)
    like.likes()
    return redirect('blog:post_detail',pk=like.pk)

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
   <link href="https://fonts.googleapis.com/css?family=Lobster|Montserrat|Russo+One" rel="stylesheet">
    <link rel= "stylesheet" href = "{% static 'css/blog.css' %}"></head>
  <body >
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">My Tech Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      {% if user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li><a href="{% url 'blog:post_new' %}">New Post</a></li>
        <li><a href="{% url 'blog:post_draft_list' %}">Draft</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      	<li> <a><strong>Welcome: {{ user.username|title }}</strong> </a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
        {% endif %}
    </div>
  </div>
</nav>

  <div class="content container loader">
    <div class="rows">
      <div class="col-sm-8">
          {% block content %}
          {% endblock %}
        </div>

      </div>

    </div>

    <div class="content container">
      <div class="rows">
        <div class="col-sm-8">
            {% block buttoncontent %}
            {% endblock %}
          </div>

        </div>
    </div>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>New Comment</h1>
<form class="" method="post">
  {% csrf_token %}
  {{form.as_p}}

  <input type="submit" class= "save btn btn-default" name="" value="Post Comment">
</form>

<script type="text/javascript">
  var editor = new MediumEditor('.editable');
</script>
{%  endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}

<form  method="post">
  {% csrf_token %}

  <p>Are you sure  you want to delete {{object}}</p>
  <input type="submit" class = "btn btn-danger" value="Delete">
  <a class="btn btn-primary" href="{% url 'blog:post_detail' pk=post.pk %}">Cancel</a>
</form>
{%  endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<h3 class="posttitle">{{post.title|safe}}</h3>
    <p>{{ post.text|safe|linebreaksbr}}</p>

    <p><strong>Author</strong>:<i> {{ post.author|title }} </i></p>

    {% if post.published_date %}
    <p class="date postdate">Published on: {{post.published_date}}</p>

    {% if user.is_authenticated %}
    <a class = "btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
      <span class="glyphicon glyphicon-pencil"></span>
    </a>

    <a class = "btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
      <span class="glyphicon glyphicon-remove"></span>
    </a>
    {% endif %}

    {% else %}

    {% if user.is_authenticated %}
    <div>
      <a class="b btn btn-primary "href="{% url 'blog:post_publish' pk=post.pk%}">Publish</a>
      <a class = "btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
        <span class="glyphicon glyphicon-pencil"></span>
      </a>

      <a class = "btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
        <span class="glyphicon glyphicon-remove"></span>
      </a>

        <br>
      </div>
    {% endif %}
    {% endif %}

    {% if post.published_date %}
    <br>
    <p><strong>COMMENTS:</strong></p>
    {% for comment in post.comments.all %}
    <ul>
    <li>{{ comment.text|safe }}

      Posted by: <strong>{{ comment.author }}</strong></li>
      <br>
    </ul>
    {% endfor %}
    {% endif %}

    {% if post.published_date %}
    <div class="row">
    <a class = "btn btn-primary " href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>
    <a class = "btn btn-primary " href="{% url 'blog:like' pk=post.pk %}">Like : {{ post.like }}</a>

    </div>
    {% endif %}

    <br>

{%  endblock %}

{% block buttoncontent %}


    {% if post.published_date %}

    <iframe src="https://www.facebook.com/plugins/share_button.php?href={{request.build_absolute_uri}}&layout=button&size=large&mobile_iframe=true&width=73&height=28&appId"
            width="73" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"
            allow="encrypted-media"></iframe>
    <br>
    <a href="https://plus.google.com/share?url={{request.build_absolute_uri}}" onclick="javascript:window.open(this.href,
    '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><img
    src="https://www.gstatic.com/images/icons/gplus-32.png" alt="Share on Google+"/></a>

    {% endif %}
{% endblock%}

blog/templates/blog/post_draft.html
{% extends 'blog/base.html' %}

{% block content %}

<div class="centerstage">

  {% for post in post_list %}

  <div class="post">
    <h1><a href= "{% url 'blog:post_detail' pk = post.pk %}">{{ post.title }}</a></h1>
    <div class="date">
      <p>{{ post.create_date|date:"D M Y" }}</p>
    </div>
  </div>

  {% endfor %}
</div>
{%  endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}

<form  class="post-form" method="post">
  {% csrf_token %}
  {{form.as_p}}

  <input type= "submit" value="Save">
</form>

<script>

  var editor = new MediumEditor('.editable');

</script>
{%  endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="centerstage">

  {% for post in post_list %}

  <div >
    <h1 class="posttitle"><a href= "{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
    <div class="date">

      {% if post.published_date %}
        <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
        <p>Comments: {{ post.comment_count.count }}</p>
        <p>Likes: {{ post.like }}</p>

      {% else %}
        <p>Created on: {{ post.create_date|date:"D M Y" }}</p>

      {% endif %}

    </div>
  </div>

  {% endfor %}
</div>
{%  endblock %}